api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('courses/', CoursesList.as_view()),
    # path('create-course/', CourseCreate.as_view()),
    # path('update-course/<int:pk>/', CourseRetrieveUpdateDestroy.as_view()),
    # path('course/<int:pk>/complete', CourseComplete.as_view()),
    path('course/<int:pk>/', CourseDetailView, name = 'course'),
    path('create-course/', CourseCreateView, name = 'course-create'),
    path('update-course/<int:pk>/', CourseUpdateView, name = 'course-update'),
    path('delete-course/<int:pk>/', CourseDeleteView, name = 'course-delete'),

    # Authentication
    path('signup/', signup),
    path('login/', login),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('timetable_app.urls')),

    # API
    path('api/', include ('api.urls')),

    # AUTH
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('change-password/', user_views.change_password, name = 'change-password'),
]

timetable_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name = 'home' ),
    path('dashboard/', dashboard, name = 'dashboard' ),

    # ============================Venue ===================================
    path('all-venues/', view_venues, name = 'view-venues'),
    path('add/venue/', add_venue, name = 'add-venue'),
    path('update/venue/<int:id>/', update_venue, name = 'update-venue'),
    path('delete/venue/<int:id>/', delete_venue, name = 'delete-venue'),

    # ============================Lecturers ===================================
    path('all-lecturers/', view_lecturers, name = 'view-lecturers'),
    path('add/lecturer/', add_lecturer, name = 'add-lecturer'),
    path('update/lecturer/<int:id>/', update_lecturer, name = 'update-lecturer'),
    path('delete/lecturer/<int:id>/', delete_lecturer, name = 'delete-lecturer'),

    # ============================Modules ===================================
    path('all-modules/', view_modules, name = 'view-modules'),
    path('add/module/', add_module, name = 'add-module'),
    path('update/module/<int:id>/', update_module, name = 'update-module'),
    path('delete/module/<int:id>/', delete_module, name = 'delete-module'),

    # ============================Courses ===================================
    path('all-courses/', view_courses, name = 'view-courses'),
    path('add/course/', add_course, name = 'add-course'),
    path('update/course/<int:id>/', update_course, name = 'update-course'),
    path('delete/course/<int:id>/', delete_course, name = 'delete-course'),

    # ============================Allocations ===================================
    path('all-intervals/', view_intervals, name = 'view-intervals'),
    path('add/interval/', add_interval, name = 'add-interval'),
    path('update/interval/<int:id>/', update_interval, name = 'update-interval'),
    path('delete/course/<int:id>/', delete_interval, name = 'delete-interval'),

    # ============================Allocations ===================================
    path('all-allocations/', view_allocations, name = 'view-allocations'),
    path('add/allocation/', add_allocation, name = 'add-allocation'),
    path('update/allocation/<int:id>/', update_allocation, name = 'update-allocation'),
    path('delete/allocation/<int:id>/', delete_allocation, name = 'delete-allocation'),

    # ============================Allocations ===================================
    path('filter-by/courses/', filterCourses, name  ='filter-courses'),
    path('allocations/pdf/<int:id>/', pdf, name = 'pdf'),
    path('view/pdf/<int:id>/', ViewPDF.as_view(), name = 'viewPdf'),
    path('download/pdf/<int:id>/', DownloadPDF.as_view(), name = 'downloadPdf'),

]

timetable_app/models.py
from django.db import models

# Create your models here.
class Day(models.Model):
    name = models.CharField(max_length = 20, unique = True)



    class Meta:
        verbose_name_plural = 'Days'

    def __str__(self):
        return self.name

class Venue(models.Model):
    name = models.CharField(max_length = 20, unique = True)
    capacity = models.PositiveIntegerField(default = 0)


    class Meta:
        verbose_name_plural = 'Venues'

    def __str__(self):
        return self.name


class Lecturer(models.Model):
    id_number = models.CharField(max_length = 50, unique = True)
    name = models.CharField(max_length = 100)
    speciality = models.CharField(max_length = 100)


    class Meta:
        verbose_name_plural = 'Lecturers'

    def __str__(self):
        return self.name


class Course(models.Model):
    code = models.CharField(max_length = 20, unique = True)
    name = models.CharField(max_length = 100)
    capacity = models.PositiveIntegerField(default = 0)

    class Meta:
        verbose_name_plural = 'Courses'

    def __str__(self):
        return self.name + ' ' +  '(' + self.code + ')'

class Module(models.Model):
    code = models.CharField(max_length = 20, unique = True)
    name = models.CharField(max_length = 100)
    course = models.ForeignKey(Course, models.SET_NULL, blank = True, null = True)

    class Meta:
        verbose_name_plural = 'Modules'

    def __str__(self):
        return self.name + ' '+ '(' + self.code + ')'

class Interval(models.Model):
    start_time = models.PositiveIntegerField()
    end_time = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'Intervals'

    def __str__(self):
        start_time = str(self.start_time)
        end_time = str(self.end_time)
        return start_time +" - "+ end_time


TYPE_CHOICES = (
    ('1', 'Tutorial / Seminar'),
    ('2', 'Lecture'),
)

class Allocation(models.Model):
    day = models.ForeignKey(Day, models.SET_NULL, blank = True, null = True)
    course  = models.ForeignKey(Course, on_delete = models.CASCADE)
    lecturer  = models.ForeignKey(Lecturer, on_delete = models.CASCADE)
    start_lesson = models.TimeField()
    end_lesson = models.TimeField()
    venue  = models.ForeignKey(Venue, on_delete = models.CASCADE)
    type = models.CharField(choices = TYPE_CHOICES, max_length = 2)
    interval = models.ForeignKey(Interval, on_delete=models.CASCADE)
    module = models.ForeignKey(Module, on_delete = models.CASCADE)

    class Meta:
        verbose_name_plural = 'Allocations'

    def __str__(self):
        return self.day + self.time

timetable_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.views import View
from xhtml2pdf import pisa
from datetime import datetime, timedelta
import random
from .models  import *
from .forms import *
from django.contrib import messages
from django.db.models import F, Q

# Create your views here.
def home(request):
    myTemplate = 'timetable/home.html'
    context = {}
    return render(request, myTemplate, context)

@login_required
def dashboard(request):
    sliced_venues = Venue.objects.all()[:5]
    sliced_modules = Module.objects.all()[:5]
    sliced_lecturers = Lecturer.objects.all()[:5]
    sliced_courses = Course.objects.all()[:5]
    venues_number = Venue.objects.all().count()
    modules_number = Module.objects.all().count()
    lecturers_number = Lecturer.objects.all().count()
    courses_number = Course.objects.all().count()

    myTemplate = 'timetable/dashboard.html'
    context = {
        'venues': sliced_venues,
        'modules': sliced_modules,
        'lecturers': sliced_lecturers,
        'courses': sliced_courses,
        'venues_number': venues_number,
        'modules_number': modules_number,
        'lecturers_number': lecturers_number,
        'courses_number': courses_number,
    }
    return render(request, myTemplate, context)

# ==================== Venue Logics ===========================================
@login_required
def view_venues(request):
    get_venues = Venue.objects.all()
    query = request.GET.get("q")
    if query:
        get_venues = get_venues.filter(name__icontains = query)
        if not get_venues:
            get_venues = Venue.objects.all()
            messages.warning(request,f'Invalid Search!')
    myTemplate = 'timetable/viewVenues.html'
    context = {
        'venues': get_venues,
    }
    return render(request, myTemplate, context)

@login_required
def add_venue(request):
    form   = addVenueForm()
    if request.method == 'POST':
        form = addVenueForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Venue added successfully!')
            return redirect('add-venue')
    else:
        add_form = addVenueForm()
    context = {
        'form': form,
    }
    myTemplate = 'timetable/addVenue.html'
    return render(request, myTemplate, context)

@login_required
def update_venue(request, id):
    instance = get_object_or_404(Venue, pk = id)
    form = updateVenueForm(request.POST or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, f'Venue has been updated successifully!')
        return redirect ('view-venues')
    context = {
        'form': form,
    }
    myTemplate = 'timetable/updateVenue.html'
    return render(request, myTemplate, context)

@login_required
def delete_venue(request, id):
    get_data = get_object_or_404(Venue, pk = id)
    get_data.delete()
    messages.success(request, f'Venue deleted successfull!')
    return redirect('view-venues')


# ==================== Lecturers Logics ===========================================
@login_required
def view_lecturers(request):
    get_lecturers = Lecturer.objects.all()
    query = request.GET.get("q")
    if query:
        get_lecturers = get_lecturers.filter(Q(name__icontains = query) |Q(id_number__icontains = query) )
        if not get_lecturers:
            get_lecturers = Lecturer.objects.all()
            messages.warning(request,f'Invalid Search!')
    myTemplate = 'timetable/viewLecturers.html'
    context = {
        'lecturers': get_lecturers,
    }
    return render(request, myTemplate, context)

@login_required
def add_lecturer(request):
    form   = addLecturerForm()
    if request.method == 'POST':
        form = addLecturerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Lecturer added successfully!')
            return redirect('add-lecturer')
    else:
        add_form = addLecturerForm()
    context = {
        'form': form,
    }
    myTemplate = 'timetable/addLecturer.html'
    return render(request, myTemplate, context)

@login_required
def update_lecturer(request, id):
    instance = get_object_or_404(Lecturer, pk = id)
    form = updateLecturerForm(request.POST or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, f'Lecturer has been updated successifully!')
        return redirect ('view-lecturers')
    context = {
        'form': form,
    }
    myTemplate = 'timetable/updateLecturer.html'
    return render(request, myTemplate, context)

@login_required
def delete_lecturer(request, id):
    get_data = get_object_or_404(Lecturer, pk = id)
    get_data.delete()
    messages.success(request, f'Lecturer deleted successfull!')
    return redirect('view-lecturers')

# ==================== Module Logics ===========================================
@login_required
def view_modules(request):
    get_modules = Module.objects.all()
    query = request.GET.get("q")
    if query:
        get_modules = get_modules.filter(Q(name__icontains = query) |Q(code__icontains = query) )
        if not get_modules:
            get_modules = Module.objects.all()
            messages.warning(request,f'Invalid Search!')
    myTemplate = 'timetable/viewModules.html'
    context = {
        'modules': get_modules,
    }
    return render(request, myTemplate, context)

@login_required
def add_module(request):
    form   = addModuleForm()
    if request.method == 'POST':
        form = addModuleForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Module added successfully!')
            return redirect('add-module')
    else:
        add_form = addModuleForm()
    context = {
        'form': form,
    }
    myTemplate = 'timetable/addModule.html'
    return render(request, myTemplate, context)

@login_required
def update_module(request, id):
    instance = get_object_or_404(Module, pk = id)
    form = updateModuleForm(request.POST or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, f'Module has been updated successifully!')
        return redirect ('view-modules')
    context = {
        'form': form,
    }
    myTemplate = 'timetable/updateModule.html'
    return render(request, myTemplate, context)

@login_required
def delete_module(request, id):
    get_data = get_object_or_404(Module, pk = id)
    get_data.delete()
    messages.success(request, f'Module deleted successfull!')
    return redirect('view-modules')

# ==================== Courses Logics ===========================================
@login_required
def view_courses(request):
    get_courses = Course.objects.all()
    query = request.GET.get("q")
    if query:
        get_courses = get_courses.filter(Q(name__icontains = query) |Q(code__icontains = query) )
        if not get_courses:
            get_courses = Course.objects.all()
            messages.warning(request,f'Invalid Search!')
    myTemplate = 'timetable/viewCourses.html'
    context = {
        'courses': get_courses,
    }
    return render(request, myTemplate, context)


def filterCourses(request):
    get_courses = Course.objects.all()
    query = request.GET.get("q")
    if query:
        get_courses = get_courses.filter(Q(name__icontains = query) |Q(code__icontains = query) )
        if not get_courses:
            get_courses = Course.objects.all()
            messages.warning(request,f'Invalid Search!')
    myTemplate = 'timetable/filterCourses.html'
    context = {
        'courses': get_courses,
    }
    return render(request, myTemplate, context)

@login_required
def add_course(request):
    form   = addCourseForm()
    if request.method == 'POST':
        form = addCourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Course added successfully!')
            return redirect('add-course')
    else:
        add_form = addCourseForm()
    context = {
        'form': form,
    }
    myTemplate = 'timetable/addCourse.html'
    return render(request, myTemplate, context)

@login_required
def update_course(request, id):
    instance = get_object_or_404(Course, pk = id)
    form = updateCourseForm(request.POST or None, instance = instance)
    if form.is_valid():
        form.save()
        messages.success(request, f'Course has been updated successifully!')
        return redirect ('view-courses')
    context = {
        'form': form,
    }
    myTemplate = 'timetable/updateCourse.html'
    return render(request, myTemplate, context)

@login_required
def delete_course(request, id):
    get_data = get_object_or_404(Course, pk = id)
    get_data.delete()
    messages.success(request, f'Course deleted successfull!')
    return redirect('view-courses')


#============================ Intervals ========================================
@login_required
def view_intervals(request):
    get_intervals = Interval.objects.all()
    query = request.GET.get("q")
    if query:
        get_intervals = get_intervals.filter(Q(start_time__icontains = query) |Q(end_time__icontains = query) )
        if not get_intervals:
            get_intervals = Interval.objects.all()
            messages.warning(request, f'Invalid Search!')
    myTemplate = 'timetable/viewIntervals.html'
    context = {
        'intervals': get_intervals,
    }
    return render(request, myTemplate, context)

@login_required
def add_interval(request):
    form   = addIntervalForm()
    if request.method == 'POST':
        form = addIntervalForm(request.POST)
        start_time = int(request.POST.get('start_time'))
        end_time = int(request.POST.get('end_time'))
        if form.is_valid():
            if start_time == end_time:

timetable_app/templates/timetable/addInterval.html
{% extends 'timetable/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add Interval {% endblock %}
{% block content%}
  <div class="outer_container">
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="contents">
            <div class="w3-card f-card">
              {% if messages %}
                  {% for message in messages %}
                      <div class="alert message alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="">&times;</span>
                          </button>
                          </div>
                  {% endfor %}
              {%  endif %}
              <div class="f-heading">
                <h3> ADD INTERVAL</h3>
              </div>
              <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-outline-info mt-5 btn-block" type="submit" name="button">Save</button>
              </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

timetable_app/templates/timetable/addLecturer.html
{% extends 'timetable/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add lecturer {% endblock %}
{% block content%}
  <div class="outer_container">
    <div class="container">
      <div class="row">
        <div class="col-md-10 offset-md-1">
          <div class="contents">
            <div class="w3-card f-card">
              {% if messages %}
                  {% for message in messages %}
                      <div class="alert message alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                          {{ message }}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="">&times;</span>
                          </button>
                          </div>
                  {% endfor %}
              {%  endif %}
              <div class="f-heading">
                <h3> ADD LECTURER</h3>
              </div>
              <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-outline-info mt-5 btn-block" type="submit" name="button">Save</button>
              </form>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock%}

timetable_app/templates/timetable/admin.html
{% extends 'timetable/base.html' %}

{% block content %}
  <div class="admin-header">
    <h1>ADMIN PANEL</h1>
  </div>

  <div class="overlay">
    <div class="d-flex text-o">
      <div class="admin-icon1">
        <a href="#">
          <i class="fa fa-plus"></i>
        </a>
      </div>
      <div class="admin-icon2">
        <a href="#">
          <i class="fa fa-eye"></i>
        </a>
      </div>
  </div>
</div>
{%endblock %}

timetable_app/templates/timetable/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href=" {% static 'fontawesome/css/all.min.css'%}">
    <!-- <link rel="stylesheet" href="  static/fontawesome/css/all.css' %} "> -->
    <!-- <link rel="stylesheet" href="static/material-design-icons-3.0.1/iconfont/material-icons.css "> -->
    <link rel="stylesheet" href="{% static 'style.css' %} ">
    <link rel="stylesheet" href="{% static 'font.css' %} ">
    <link rel="stylesheet" href="{% static 'css/w3.css' %} ">
    <title>OTMS | {% block title %} {% endblock %}</title>
  </head>
  <body class="">
    <div>
      <nav class="navbar bg-info fixed-top navbar-expand-lg">
        <a class="navbar-brand" href="{% url 'home' %}">MNMA LOGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="">
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <div class="w3-dropdown-hover mr-5 pr-3">
                <a  class=" nav-link " href="#">Add</a>
                <div class="w3-dropdown-content bg-info w3-bar-block ad-dropdown">
                  <a href="{% url 'add-allocation' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Allocation</a>
                  <a href="{% url 'add-interval' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Interval</a>
                  <a href="{% url 'add-course' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Course</a>
                  <a href="{% url 'add-lecturer' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Lecturer</a>
                  <a href="{% url 'add-module' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Module</a>
                  <a href="{% url 'add-venue' %}" class="w3-bar-item btn"><i class="fa fa-plus mr-2"></i>Add Venue</a>
                </div>
              </div>
          </ul>
          <div class="w3-dropdown-hover mr-5 pr-3">
              <a  class=" nav-link " href="#"><i class="fa fa-cogs mr-2"></i>Settings</a>
              <div class="w3-dropdown-content bg-info w3-bar-block ad-dropdown">
                <a href="{% url 'change-password' %}" class="w3-bar-item "><i class="fa fa-lock mr-2"></i> Change <span style="margin: 0 0 0 28px;">Password</span></a>
                <a href="{% url 'logout' %}" class="w3-bar-item"><i class="fa fa-power-off mr-2"></i> Logout</a>
              </div>
            </div>
          {% endif %}
        </div>
      </nav>
    </div>
      {% if user.is_authenticated %}
      <div class="w3-sidebar w3-bar-block bg-info "
      style="
        width:15%;
        padding-top: 40px;
        float: left;
       ">
        <a href="{% url 'view-allocations' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Allocations</a>
        <a href="{% url 'view-courses' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Courses</a>
        <a href="{% url 'view-intervals' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Intervals</a>
        <a href="{% url 'view-modules' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Modules</a>
        <a href="{% url 'view-lecturers' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Lectures</a>
        <a href="{% url 'view-venues' %}" class="w3-bar-item btn"><i class="fa fa-eye mr-2"></i>View Venues</a>
      </div>


        <div class="page">
          {% endif %}
          {% block content %} {% endblock %}
        </div>

      <footer class="footer bg-info">
         <p>Copyright &copy Mwalimu Nyerere Memorial Academy 2020 |  All rights reserved</p>
      </footer>



      <script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
      <script type="text/javascript" src="{% static 'fontawesome/js/all.min.js'%}"></script>
      <!-- <script type="text/javascript" src="static/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="static/fontawesome/js/all.min.js"></script> -->

    </body>
  </html>

timetable_app/templates/timetable/dashboard.html
{% extends 'timetable/base.html' %}
{% block title %} Dashboard {% endblock %}
{% block content%}
  <div class="outer-container">
    <div class="container">
      <div class="row">
        <div class="col-12 ">
        <div class="contents">
          {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="">&times;</span>
                      </button>
                      </div>
              {% endfor %}
          {%  endif %}
            <div class="heading mb-4 bg-info">
              <h3>DASHBOARD</h3>
            </div>
            <div class="w3-card d-flex">
              <a class="col-3 summary" href="{% url 'view-venues' %}">
                <span><h3>VENUES</h3></span>
                <h2>
                  {{ venues_number }}
                </h2>
              </a>
              <a class="col-3 summary" href="{% url 'view-modules' %}">
                <span><h3>MODULES</h3></span>
                <h2>
                  {{ modules_number }}
                </h2>
              </a>
              <a class="col-3 summary" href="{% url 'view-courses' %}">
                <span><h3>COURSES</h3></span>
                <h2>
                  {{ courses_number }}
                </h2>
              </a>
              <a class="col-3 summary" href="{% url 'view-lecturers' %}">
                <span><h3>LECTURERS</h3></span>
                <h2>
                  {{ lecturers_number }}
                </h2>
              </a>
          </div>

          <div class="w3-card col-12 mt-4 d-flex">
            <table class="col-6 table table-hover table-bordered table-striped">
              <tr>
                <th>Venues</th>
              </tr>
              <tbody>
                {% for venue in venues %}
                <tr>
                  <td> {{ venue.name }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <table class="col-6 table table-hover table-bordered table-striped">
              <tr>
                <th>Modules</th>
              </tr>
              <tbody>
                {% for module in modules %}
                <tr>
                  <td> {{ module.name }}  ({{ module.code }}) </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="w3-card col-12 mt-4 d-flex">
            <table class="col-6 table table-hover table-bordered table-striped">
              <tr>
                <th>Courses</th>
              </tr>
              <tbody>
                {% for course in courses %}
                <tr>
                  <td>  {{ course.name }} ({{ course.code }}) </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <table class="col-6 table table-hover table-bordered table-striped">
              <tr>
                <th>Lecturers</th>
              </tr>
              <tbody>
                {% for lecturer in lecturers %}
                <tr>
                  <td> {{ lecturer.name }} </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

timetable_app/templates/timetable/pdfdownloadable.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <style>
      body {
        font-size: 10px;
      }
      .heading {
        background: rgba(0, 130, 170, 0.7);
        color: #ffffff;
        padding: 10px 0 10px 0;
        text-align: center;
        font-size: 15px;
      }
      .table {
        width: 100%;
        border: 1px solid #000000;
      }
      .table th {
        height: 50px;
      }
      td {
        text-align: center;
        height: 30px;
      }

      footer {
        background: rgba(0, 130, 170, 0.7);
        color: #ffffff;
        text-align: center;
        margin: 20px 0 0 0;
        padding: 20px 0 20px 0;
      }
    </style>
    <title>MNMA Timetable PDF</title>
  </head>
  <body>
    <div class="outer-container">
    <div class="container">
      <div class="row">
        <div class="contents">
          <div class="col-md-12">
            <div class="heading">
              <h2> {{ course.name }} ({{course.code}}) (pdf)</h2>
            </div>
            <table class="table">
                <tr>
                    <!-- <thead class="thead-dark"> -->
                    <thead>
                      <th >Day</th>
                      <th >Module Name</th>
                      <th >Lecturer Name</th>
                      <th >Type</th>
                      <th >Venue</th>
                      <th >Time</th>
                    </thead>
                </tr>
                <tbody>
                  {% for day in days %}
                    <td> <strong>{{ day.name }}</strong></td>
                    <tr>
                      {% for allocation in allocations %}
                        {% if allocation.day == day %}
                          <td colspan="1"></td>
                          <td>{{ allocation.module.code }}</td>
                          <td>{{ allocation.lecturer.name }}</td>
                          <td>{{ allocation.get_type_display }}</td>
                          <td>{{ allocation.venue.name }}</td>
                          <td>{{ allocation.start_lesson| time:"H:i" }} - {{ allocation.end_lesson | time:"H:i" }}</td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="footer">
      <p>Copyright &copy Mwalimu Nyerere Memorial Academy 2020 |  All rights reserved</p>
    </footer>

  </body>
</html>

timetable_app/templates/timetable/timetable.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="">
      welcome to our online timetable!!!
    </div>
  </body>
</html>